lib/code_exchange_web/router.ex
defmodule CodeExchangeWeb.Router do
  use CodeExchangeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {CodeExchangeWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CodeExchangeWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CodeExchangeWeb do
    pipe_through :browser

    live "/", HomeLive
    live "/counter", CounterLive
    live "/discuss", DiscussLive
    live "/code", CodeLive
  end

  scope "/auth", CodeExchangeWeb do
    pipe_through :browser

    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", CodeExchangeWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: CodeExchangeWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/code_exchange_web/views/layout_view.ex
defmodule CodeExchangeWeb.LayoutView do
  use CodeExchangeWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/code_exchange_web/templates/layout/_head.heex
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta name="csrf-token" content={csrf_token_value()}>
  <%= live_title_tag assigns[:page_title] || "Discuss", suffix: " · Phoenix Framework" %>
  <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
  <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  <script>
    <%= if @conn.assigns.user do %>
      window.userToken = "<%= Phoenix.Token.sign(Discuss.Endpoint, "key", @conn.assigns.user.id) %>"
    <% end %>
  </script>
</head>

lib/code_exchange_web/templates/layout/_head.html.heex
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta name="csrf-token" content={csrf_token_value()}>
  <%= live_title_tag assigns[:page_title] || "Discuss", suffix: " · Phoenix Framework" %>
  <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
  <script src="https://kit.fontawesome.com/26d6de301e.js"></script>
  <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  <script>
  </script>
</head>

lib/code_exchange_web/templates/layout/_header.html.heex
<header id="navmenu">
  <nav class="relative container mx-auto p-6">
    <div class="flex items-center justify-around">
      
      <!-- Logo -->
      <div class="mr-8">
        <%= live_redirect to: Routes.live_path(@conn, CodeExchangeWeb.HomeLive), class: "nav-link hover:text-darkGrayBlue" do %>
          Logo
        <% end %> 
      </div>

      <!-- Menu Items -->
      <div class="hidden mx-8 space-x-8 md:flex">
        <%= live_redirect to: Routes.live_path(@conn, CodeExchangeWeb.CodeLive), class: "nav-link hover:text-darkGrayBlue" do %>
          Manage
        <% end %> 
        <%= live_redirect to: Routes.live_path(@conn, CodeExchangeWeb.DiscussLive), class: "nav-link hover:text-darkGrayBlue" do %>
          Discuss
        <% end %>
      </div>
      <div class="github text-lg">
      <%= if @conn.assigns[:user] do %>
        <%= link to: Routes.auth_path(@conn, :signout), class: "nav-link hover:text-darkGrayBlue" do %>
          Sign out
        <% end %>   
      <% else %>
        <%= link to: Routes.auth_path(@conn, :request, "github"), class: "nav-link hover:text-darkGrayBlue" do %>
          Sign in
        <% end %>
      <% end %>
      </div>
    </div>
  </nav>
</header>

lib/code_exchange_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/code_exchange_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/code_exchange_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <%= render "_head.html", assigns %>
  <body>
    <%= render "_header.html", assigns %>
    <%= @inner_content %>
  </body>
</html>